# Generated by Django 3.2.7 on 2021-09-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='기부단체 이름')),
                ('thumbnail', models.ImageField(upload_to='%Y/%m/%d', verbose_name='썸네일')),
                ('link', models.CharField(max_length=200, verbose_name='단체 링크')),
                ('context', models.TextField(verbose_name='간단한 설명')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='사용자이메일')),
                ('name', models.CharField(max_length=30, verbose_name='사용자 이름')),
                ('plan', models.CharField(choices=[('simple', 'simple'), ('premium', 'premium'), ('nobless', 'nobless')], max_length=20, verbose_name='사용자 구독 플랜')),
                ('password', models.CharField(max_length=30, verbose_name='비밀번호')),
            ],
        ),
        migrations.CreateModel(
            name='User_Choiced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField(verbose_name='코인')),
                ('date', models.DateTimeField()),
                ('orga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization', verbose_name='기부단체')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user', verbose_name='유저')),
            ],
        ),
    ]
