# Generated by Django 3.2.7 on 2021-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('nobless', 'nobless')], max_length=20, verbose_name='사용자 구독 플랜'),
        ),
    ]
